package com.heyuhuan.admin.pojo;

public class TransportOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_order_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_order_detail.toid
     *
     * @mbggenerated
     */
    private Integer toid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_order_detail.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_order_detail.amount
     *
     * @mbggenerated
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_order_detail.amountunit
     *
     * @mbggenerated
     */
    private Byte amountunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_order_detail.length
     *
     * @mbggenerated
     */
    private Float length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_order_detail.width
     *
     * @mbggenerated
     */
    private Float width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transport_order_detail.height
     *
     * @mbggenerated
     */
    private Float height;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_order_detail.id
     *
     * @return the value of transport_order_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_order_detail.id
     *
     * @param id the value for transport_order_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_order_detail.toid
     *
     * @return the value of transport_order_detail.toid
     *
     * @mbggenerated
     */
    public Integer getToid() {
        return toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_order_detail.toid
     *
     * @param toid the value for transport_order_detail.toid
     *
     * @mbggenerated
     */
    public void setToid(Integer toid) {
        this.toid = toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_order_detail.name
     *
     * @return the value of transport_order_detail.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_order_detail.name
     *
     * @param name the value for transport_order_detail.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_order_detail.amount
     *
     * @return the value of transport_order_detail.amount
     *
     * @mbggenerated
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_order_detail.amount
     *
     * @param amount the value for transport_order_detail.amount
     *
     * @mbggenerated
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_order_detail.amountunit
     *
     * @return the value of transport_order_detail.amountunit
     *
     * @mbggenerated
     */
    public Byte getAmountunit() {
        return amountunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_order_detail.amountunit
     *
     * @param amountunit the value for transport_order_detail.amountunit
     *
     * @mbggenerated
     */
    public void setAmountunit(Byte amountunit) {
        this.amountunit = amountunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_order_detail.length
     *
     * @return the value of transport_order_detail.length
     *
     * @mbggenerated
     */
    public Float getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_order_detail.length
     *
     * @param length the value for transport_order_detail.length
     *
     * @mbggenerated
     */
    public void setLength(Float length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_order_detail.width
     *
     * @return the value of transport_order_detail.width
     *
     * @mbggenerated
     */
    public Float getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_order_detail.width
     *
     * @param width the value for transport_order_detail.width
     *
     * @mbggenerated
     */
    public void setWidth(Float width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transport_order_detail.height
     *
     * @return the value of transport_order_detail.height
     *
     * @mbggenerated
     */
    public Float getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transport_order_detail.height
     *
     * @param height the value for transport_order_detail.height
     *
     * @mbggenerated
     */
    public void setHeight(Float height) {
        this.height = height;
    }
}