package com.heyuhuan.admin.pojo;

import java.util.Date;

public class Vehicle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.number_plate
     *
     * @mbggenerated
     */
    private String numberPlate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.longitude
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.latitude
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.temperature
     *
     * @mbggenerated
     */
    private Float temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.humidity
     *
     * @mbggenerated
     */
    private Float humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.loadweight
     *
     * @mbggenerated
     */
    private Float loadweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.loadvolume
     *
     * @mbggenerated
     */
    private Float loadvolume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.id
     *
     * @return the value of vehicle.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.id
     *
     * @param id the value for vehicle.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.create_date
     *
     * @return the value of vehicle.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.create_date
     *
     * @param createDate the value for vehicle.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.modify_date
     *
     * @return the value of vehicle.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.modify_date
     *
     * @param modifyDate the value for vehicle.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.phone
     *
     * @return the value of vehicle.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.phone
     *
     * @param phone the value for vehicle.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.province
     *
     * @return the value of vehicle.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.province
     *
     * @param province the value for vehicle.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.number_plate
     *
     * @return the value of vehicle.number_plate
     *
     * @mbggenerated
     */
    public String getNumberPlate() {
        return numberPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.number_plate
     *
     * @param numberPlate the value for vehicle.number_plate
     *
     * @mbggenerated
     */
    public void setNumberPlate(String numberPlate) {
        this.numberPlate = numberPlate == null ? null : numberPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.longitude
     *
     * @return the value of vehicle.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.longitude
     *
     * @param longitude the value for vehicle.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.latitude
     *
     * @return the value of vehicle.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.latitude
     *
     * @param latitude the value for vehicle.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.state
     *
     * @return the value of vehicle.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.state
     *
     * @param state the value for vehicle.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.temperature
     *
     * @return the value of vehicle.temperature
     *
     * @mbggenerated
     */
    public Float getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.temperature
     *
     * @param temperature the value for vehicle.temperature
     *
     * @mbggenerated
     */
    public void setTemperature(Float temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.humidity
     *
     * @return the value of vehicle.humidity
     *
     * @mbggenerated
     */
    public Float getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.humidity
     *
     * @param humidity the value for vehicle.humidity
     *
     * @mbggenerated
     */
    public void setHumidity(Float humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.loadweight
     *
     * @return the value of vehicle.loadweight
     *
     * @mbggenerated
     */
    public Float getLoadweight() {
        return loadweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.loadweight
     *
     * @param loadweight the value for vehicle.loadweight
     *
     * @mbggenerated
     */
    public void setLoadweight(Float loadweight) {
        this.loadweight = loadweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.loadvolume
     *
     * @return the value of vehicle.loadvolume
     *
     * @mbggenerated
     */
    public Float getLoadvolume() {
        return loadvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.loadvolume
     *
     * @param loadvolume the value for vehicle.loadvolume
     *
     * @mbggenerated
     */
    public void setLoadvolume(Float loadvolume) {
        this.loadvolume = loadvolume;
    }
}