package com.heyuhuan.admin.pojo;

public class XxAreaWithBLOBs extends XxArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.full_name
     *
     * @mbggenerated
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.boundaries_la
     *
     * @mbggenerated
     */
    private String boundariesLa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.boundaries_lo
     *
     * @mbggenerated
     */
    private String boundariesLo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.boundaries
     *
     * @mbggenerated
     */
    private String boundaries;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.full_name
     *
     * @return the value of xx_area.full_name
     *
     * @mbggenerated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.full_name
     *
     * @param fullName the value for xx_area.full_name
     *
     * @mbggenerated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.boundaries_la
     *
     * @return the value of xx_area.boundaries_la
     *
     * @mbggenerated
     */
    public String getBoundariesLa() {
        return boundariesLa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.boundaries_la
     *
     * @param boundariesLa the value for xx_area.boundaries_la
     *
     * @mbggenerated
     */
    public void setBoundariesLa(String boundariesLa) {
        this.boundariesLa = boundariesLa == null ? null : boundariesLa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.boundaries_lo
     *
     * @return the value of xx_area.boundaries_lo
     *
     * @mbggenerated
     */
    public String getBoundariesLo() {
        return boundariesLo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.boundaries_lo
     *
     * @param boundariesLo the value for xx_area.boundaries_lo
     *
     * @mbggenerated
     */
    public void setBoundariesLo(String boundariesLo) {
        this.boundariesLo = boundariesLo == null ? null : boundariesLo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.boundaries
     *
     * @return the value of xx_area.boundaries
     *
     * @mbggenerated
     */
    public String getBoundaries() {
        return boundaries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.boundaries
     *
     * @param boundaries the value for xx_area.boundaries
     *
     * @mbggenerated
     */
    public void setBoundaries(String boundaries) {
        this.boundaries = boundaries == null ? null : boundaries.trim();
    }
}