package com.heyuhuan.admin.pojo;

import java.util.Date;

public class XxArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.parent
     *
     * @mbggenerated
     */
    private Long parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.orders
     *
     * @mbggenerated
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_area.tree_path
     *
     * @mbggenerated
     */
    private String treePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.id
     *
     * @return the value of xx_area.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.id
     *
     * @param id the value for xx_area.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.parent
     *
     * @return the value of xx_area.parent
     *
     * @mbggenerated
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.parent
     *
     * @param parent the value for xx_area.parent
     *
     * @mbggenerated
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.create_date
     *
     * @return the value of xx_area.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.create_date
     *
     * @param createDate the value for xx_area.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.modify_date
     *
     * @return the value of xx_area.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.modify_date
     *
     * @param modifyDate the value for xx_area.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.orders
     *
     * @return the value of xx_area.orders
     *
     * @mbggenerated
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.orders
     *
     * @param orders the value for xx_area.orders
     *
     * @mbggenerated
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.name
     *
     * @return the value of xx_area.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.name
     *
     * @param name the value for xx_area.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_area.tree_path
     *
     * @return the value of xx_area.tree_path
     *
     * @mbggenerated
     */
    public String getTreePath() {
        return treePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_area.tree_path
     *
     * @param treePath the value for xx_area.tree_path
     *
     * @mbggenerated
     */
    public void setTreePath(String treePath) {
        this.treePath = treePath == null ? null : treePath.trim();
    }
}