package com.heyuhuan.admin.mapper;

import com.heyuhuan.admin.pojo.TransportOrderDetail;

public interface TransportOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_order_detail
     *
     * @mbggenerated
     */
    int insert(TransportOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(TransportOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_order_detail
     *
     * @mbggenerated
     */
    TransportOrderDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TransportOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transport_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TransportOrderDetail record);
}