package com.heyuhuan.admin.mapper;

import com.heyuhuan.admin.pojo.XxArea;
import com.heyuhuan.admin.pojo.XxAreaWithBLOBs;

import java.util.List;

public interface XxAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_area
     *
     * @mbggenerated
     */
    int insert(XxAreaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_area
     *
     * @mbggenerated
     */
    int insertSelective(XxAreaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_area
     *
     * @mbggenerated
     */
    XxAreaWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XxAreaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(XxAreaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XxArea record);

    List<XxArea> findList();

}